spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/springboot_review?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:123456}

logging:
  level:
    root: info
    com.lisaj7.springbootreview: debug